index:
    path: /
    controller: App\Controller\SiteController::index

get-photo-names:
    path: /get-photo-names
    controller: App\Controller\SiteController::getPhotoNames

photo-upload:
    path: /photo-upload
    controller: App\Controller\PhotoUploadController::buildForm